apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeatureMembership
metadata:
  name: {{ .Values.GKEHubFeatureMembership.name }}
  namespace: {{ .Values.namespace }}
spec:
  projectRef:
    external: {{ .Values.projectRef }}
  location: {{ .Values.GKEHubFeatureMembership.location }}
  membershipRef:
    external: {{ .Values.GKEHubFeatureMembership.membershipRef }}
  featureRef:
    external: {{ .Values.GKEHubFeatureMembership.featureRef }}
  configmanagement:
    configSync:
      sourceFormat: {{ .Values.GKEHubFeatureMembership.sourceFormat }}
      git:
        syncRepo: {{ .Values.GKEHubFeatureMembership.git.syncRepo }}
        syncBranch: {{ .Values.GKEHubFeatureMembership.git.syncBranch}}
        policyDir: {{ .Values.GKEHubFeatureMembership.git.policyDir }}
        syncWaitSecs: "20"
        syncRev: {{ .Values.GKEHubFeatureMembership.git.syncRev }}
        secretType: {{ .Values.GKEHubFeatureMembership.git.secretType }}
    policyController:
      enabled: {{ .Values.GKEHubFeatureMembership.policyController.enabled }}
      #exemptableNamespaces:
       # - "test-namespace"
      referentialRulesEnabled: {{ .Values.GKEHubFeatureMembership.policyController.referentialRulesEnabled }}
      logDeniesEnabled: {{ .Values.GKEHubFeatureMembership.policyController.logDeniesEnabled }}
      templateLibraryInstalled: {{ .Values.GKEHubFeatureMembership.policyController.templateLibraryInstalled }}
      auditIntervalSeconds: "20"
    binauthz:
      enabled: {{ .Values.GKEHubFeatureMembership.binauthz }}
    hierarchyController:
      enabled: {{ .Values.GKEHubFeatureMembership.hierarchyController.enabled }}
      enablePodTreeLabels: {{ .Values.GKEHubFeatureMembership.hierarchyController.enablePodTreeLabels }}
      enableHierarchicalResourceQuota: {{ .Values.GKEHubFeatureMembership.hierarchyController.enableHierarchicalResourceQuota }}