apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubMembership
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.projectid }}
  name: {{ .Values.GKEHubMembership.name }}
  namespace: {{ .Values.namespace }}
spec:
  location: {{ .Values.GKEHubMembership.location }}
  authority:
    # Issuer must contain a link to a valid JWT issuer. Your ContainerCluster is one.
    issuer: {{ .Values.GKEHubMembership.authorityissuer }}
  endpoint:
    gkeCluster:
      resourceRef:
        external: {{ .Values.GKEHubMembership.gkeCluster }}