apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  annotations:
    cnrm.cloud.google.com/force-destroy: "false"
    cnrm.cloud.google.com/project-id: {{ .Values.project }}
  labels:
    label-one: {{ .Values.storage.label }}
  # StorageBucket names must be globally unique. Replace ${PROJECT_ID?} with your project ID.
  name: {{ .Values.storage.name }}
  namespace: {{ .Values.Namespace.name }}