apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstance
metadata:
  annotations:
    cnrm.cloud.google.com/allow-stopping-for-update: "false"
    cnrm.cloud.google.com/project-id: {{ .Values.projectId }}
  name: {{ .Values.compInstance.name }}
  namespace: {{ .Values.namespace}}
  labels:
    created-from: "template"
    override-type: "largermachine"
spec:
  machineType: "{{ .Values.compInstance.machinetype }}"
  instanceTemplateRef:
    name: "{{ .Values.compInstanceTemplate.name }}"
  zone: "{{ .Values.zone }}"
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeDisk
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.projectId }}
  name: {{ .Values.compDisk.name }}
  namespace: {{ .Values.namespace }}
spec:
  physicalBlockSizeBytes: 4096
  size: 1
  type: pd-ssd
  location: "{{ .Values.location }}"
  replicaZones:
    - "{{ .Values.replicazone.eastb }}"
    - "{{ .Values.replicazone.eastc }}"

---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstanceTemplate
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.projectId }}
  name: {{ .Values.compInstanceTemplate.name }}
  namespace: {{ .Values.namespace}}
spec:
  machineType: "{{ .Values.compInstanceTemplate.machinetype }}"
  region: "{{ .Values.region }}"
  disk:
    - sourceDiskRef:
        name: "{{ .Values.compDisk.name }}"
      boot: true
  networkInterface:
    - networkRef:
        external: "{{ .Values.externalNetwork.name }}"
